{{template "header" .}}
<div class="container-fluid">
  <h1 class="h3">Publisher Payout Account</h1>
  <p class="text-muted">Payment-account, identity-verification, and bank details are entered only on Stripe-hosted pages. W8M stores only the opaque Connect account identifier, never full account or routing numbers.</p>
  {{if .Other.PaymentMessage}}<div class="alert alert-success">{{.Other.PaymentMessage}}</div>{{end}}
  <div class="card border-success"><div class="card-body">
    <h2 class="h5">Open a Hosted Payout Account</h2><p>Choose the two-letter country or region code for the operating entity. After hosted verification is complete, the binding still requires independent review.</p>
    <form method="post" action="hostedpayment?action=payoutOnboarding">{{.Other.CSRFInput}}<input type="hidden" name="pub_id" value="{{.Other.PaymentScope.PartyID}}"><label>Country or region code</label><input class="form-control" name="country" minlength="2" maxlength="2" value="US" required><label>Idempotency request key</label><input class="form-control" name="request_key" maxlength="128" required><label>Reason</label><input class="form-control" name="reason" maxlength="500" required><button class="btn btn-success mt-2" type="submit">Enter Hosted Onboarding</button></form>
  </div></div>
  <h2 class="h4 mt-4">Payout Account Bindings</h2><div class="table-responsive"><table class="table table-sm table-striped"><thead><tr><th>ID</th><th>Opaque Provider Identifier</th><th>Hosted Setup Ready</th><th>Status</th><th>Action</th></tr></thead><tbody>
    {{range .Other.PaymentBindings}}<tr><td>{{.ID}}</td><td><code>{{.ProviderToken}}</code>{{if .Country.Valid}}<br><small>{{.Country.String}}</small>{{end}}</td><td>{{.ProviderReady}}</td><td>{{.Status}}</td><td>{{if or (eq .Status "Proposed") (and (eq .Status "Revoked") .RevokedBy.Valid (eq .RevokedBy.String "provider:stripe"))}}<form method="post" action="hostedpayment?action=refreshOnboarding">{{$.Other.CSRFInput}}<input type="hidden" name="pub_id" value="{{$.Other.PaymentScope.PartyID}}"><input type="hidden" name="binding_id" value="{{.ID}}"><input type="hidden" name="binding_version" value="{{.Version}}"><input name="request_key" maxlength="128" placeholder="New idempotency request key" required><input name="reason" maxlength="500" placeholder="Reason for continuing onboarding" required><button class="btn btn-sm btn-outline-success" type="submit">Continue Hosted Onboarding</button></form>{{else if eq .Status "Ready"}}Awaiting independent review{{else if eq .Status "Approved"}}Approved{{else}}Revoked{{end}}</td></tr>{{else}}<tr><td colspan="5">No hosted payout account has been established.</td></tr>{{end}}
  </tbody></table></div>
  <h2 class="h4 mt-4">Settlement Statements</h2><div class="table-responsive"><table class="table table-sm"><thead><tr><th>ID</th><th>Period</th><th>Amount</th><th>Status</th></tr></thead><tbody>{{range .Other.PaymentStatements}}<tr><td>{{.ID}}</td><td>{{.PeriodStart}} to {{.PeriodEnd}}</td><td>{{.TotalAmount}} {{.Currency}}</td><td>{{.Status}}</td></tr>{{else}}<tr><td colspan="4">No settlement statements.</td></tr>{{end}}</tbody></table></div>
  <h2 class="h4 mt-4">Payout Progress</h2><div class="table-responsive"><table class="table table-sm table-striped"><thead><tr><th>ID</th><th>Statement</th><th>Amount</th><th>Status</th><th>Updated</th></tr></thead><tbody>{{range .Other.PaymentOperations}}<tr><td>{{.ID}}</td><td>#{{.StatementID}}</td><td>{{.Amount}} {{.Currency}}</td><td>{{.Status}}</td><td>{{.UpdatedAt}}</td></tr>{{else}}<tr><td colspan="5">No payout operations.</td></tr>{{end}}</tbody></table></div>
</div>
{{template "footer" .}}
