{{ template "header" .}}
<h1 class="h2">流量质量审查</h1>
<p class="text-muted">规则判断与基础设施错误分开记录。所有拦截都需要完整证据、人工复核和可回滚的规则版本。</p>
{{with .Other.QualityMessage}}<div class="alert alert-success">{{.}}</div>{{end}}
<div class="card mb-3"><div class="card-body"><h2 class="h5">选择审查范围</h2><div class="form-row">
<form class="form-inline mr-3" method="get" action="trafficquality"><input type="hidden" name="action" value="topicsAdv"><label>广告主 ID <input class="form-control ml-2" type="number" min="1" name="adv_id" required></label><button class="btn btn-outline-danger ml-2" type="submit">查看</button></form>
<form class="form-inline mr-3" method="get" action="trafficquality"><input type="hidden" name="action" value="topicsPub"><label>媒体 ID <input class="form-control ml-2" type="number" min="1" name="pub_id" required></label><button class="btn btn-outline-info ml-2" type="submit">查看</button></form>
<form class="form-inline" method="get" action="trafficquality"><input type="hidden" name="action" value="topicsPartner"><label>外部需求方 ID <input class="form-control ml-2" type="number" min="1" name="partner_id" required></label><button class="btn btn-outline-secondary ml-2" type="submit">查看</button></form>
</div></div></div>
<div class="card mb-3"><div class="card-body"><h2 class="h5">新建规则草案</h2><form method="post" action="trafficquality?action=createRule">{{.Other.CSRFInput}}<div class="form-row">
<div class="form-group col-md-3"><label>规则键</label><input class="form-control" name="rule_key" pattern="[a-z][a-z0-9_.-]{2,63}" required></div>
<div class="form-group col-md-3"><label>信号</label><select class="form-control" name="signal"><option>Replay</option><option>ImpossibleSequence</option><option>InvalidOriginApp</option><option>MalformedIdentity</option><option>AbnormalRate</option><option>AbnormalCTR</option><option>Automation</option><option>PartnerPolicy</option></select></div>
<div class="form-group col-md-2"><label>动作</label><select class="form-control" name="rule_action"><option>Observe</option><option>Flag</option><option>Throttle</option><option>Reject</option><option>Quarantine</option></select></div>
<div class="form-group col-md-2"><label>范围</label><select class="form-control" name="scope_type"><option>Global</option><option>Advertiser</option><option>Publisher</option><option>Partner</option></select></div>
<div class="form-group col-md-2"><label>范围 ID</label><input class="form-control" type="number" min="0" name="scope_id" value="0" required></div>
</div><div class="form-row">
<div class="form-group col-md-2"><label>阈值</label><input class="form-control" type="number" min="0" step="0.000001" name="threshold" required></div>
<div class="form-group col-md-2"><label>窗口（秒）</label><input class="form-control" type="number" min="1" max="2592000" name="window_seconds" value="60" required></div>
<div class="form-group col-md-2"><label>原因代码</label><input class="form-control" name="reason_code" pattern="[a-z][a-z0-9_.-]{2,63}" required></div>
<div class="form-group col-md-2"><label>证据保留（小时）</label><input class="form-control" type="number" min="1" max="720" name="evidence_hours" value="24" required></div>
<div class="form-group col-md-2"><label>汇总保留（天）</label><input class="form-control" type="number" min="365" max="2555" name="aggregate_days" value="400" required></div>
<div class="form-group col-md-2"><label>误判上限（基点）</label><input class="form-control" type="number" min="0" max="10000" name="false_positive_bps" value="100" required></div>
</div><label>变更原因</label><input class="form-control" name="reason" maxlength="500" required><button class="btn btn-primary mt-2" type="submit">保存草案</button></form></div></div>
<h2 class="h4">规则版本</h2><div class="table-responsive"><table class="table table-sm table-striped"><thead><tr><th>ID</th><th>键 / 版本</th><th>信号</th><th>动作</th><th>范围</th><th>阈值 / 窗口</th><th>模式</th><th>发布</th></tr></thead><tbody>{{range .Other.QualityRules}}<tr><td>{{.ID}}</td><td><code>{{.Key}}@{{.Version}}</code></td><td>{{.Signal}}</td><td>{{.Action}}</td><td>{{.Scope.Type}} {{.Scope.ID}}</td><td>{{printf "%.6f" .Threshold}} / {{.WindowSeconds}} 秒</td><td>{{.Mode}}{{if eq .Mode "Canary"}}（{{.CanaryBasisPoints}} bp）{{end}}</td><td><form method="post" action="trafficquality?action=setMode">{{$.Other.CSRFInput}}<input type="hidden" name="rule_id" value="{{.ID}}"><input type="hidden" name="expected_mode" value="{{.Mode}}"><select name="next_mode"><option>Observe</option><option>Canary</option><option>Active</option><option>Disabled</option></select><input type="number" name="canary_bps" min="0" max="10000" value="0" aria-label="灰度基点"><input name="reason" maxlength="500" placeholder="原因" required><button class="btn btn-sm btn-outline-primary" type="submit">更新</button></form></td></tr>{{else}}<tr><td colspan="8">暂无规则。</td></tr>{{end}}</tbody></table></div>
<h2 class="h4">最近 24 小时规则健康度</h2><table class="table table-sm"><thead><tr><th>规则</th><th>判断 / 命中 / 执行</th><th>有效 / 无效</th><th>申诉 / 支持</th><th>误判率</th><th>建议</th></tr></thead><tbody>{{range .Other.QualityHealth}}<tr><td><code>{{.RuleKey}}@{{.RuleVersion}}</code></td><td>{{.Decisions}} / {{.Matched}} / {{.Enforced}}</td><td>{{.ValidTraffic}} / {{.InvalidTraffic}}</td><td>{{.Appeals}} / {{.AppealsUpheld}}</td><td>{{.FalsePositiveBasisPoints}} bp（上限 {{.FalsePositiveLimitBPS}}）</td><td>{{if .RollbackRecommended}}<span class="badge badge-danger">建议回滚</span>{{else}}正常{{end}}</td></tr>{{else}}<tr><td colspan="6">暂无规则健康数据。</td></tr>{{end}}</tbody></table>
{{with .Other.QualityScope}}{{if ne .Type "Global"}}<h2 class="h4">审查案件：{{.Type}} {{.ID}}</h2>{{end}}{{end}}
<div class="table-responsive"><table class="table table-sm"><thead><tr><th>案件</th><th>规则</th><th>信号 / 证据</th><th>动作</th><th>状态</th><th>操作</th></tr></thead><tbody>{{range .Other.QualityCases}}<tr><td>#{{.ID}}<br><small>{{.ObservedAt}}</small></td><td><code>{{.RuleKey}}@{{.RuleVersion}}</code><br>{{.ReasonCode}}</td><td>{{.Signal}}：{{printf "%.6f" .ObservedValue}} / {{printf "%.6f" .Threshold}}<br>{{.Evidence}}{{if .SafeSummary.Valid}}：{{.SafeSummary.String}}{{end}}</td><td>{{.ConfiguredAction}} → {{.AppliedAction}}</td><td>{{.Status}}（v{{.Version}}）</td><td>{{if eq .Status "Open"}}<form method="post" action="trafficquality?action=resolve">{{$.Other.CSRFInput}}<input type="hidden" name="case_id" value="{{.ID}}"><input type="hidden" name="case_version" value="{{.Version}}"><input type="hidden" name="scope_type" value="{{.Scope.Type}}"><input type="hidden" name="scope_id" value="{{.Scope.ID}}"><select name="resolution"><option>ValidTraffic</option><option>InvalidTraffic</option></select><input name="reason" maxlength="500" placeholder="复核原因" required><button class="btn btn-sm btn-outline-primary" type="submit">结案</button></form>{{else if eq .Status "Appealed"}}<form method="post" action="trafficquality?action=resolveAppeal">{{$.Other.CSRFInput}}<input type="hidden" name="case_id" value="{{.ID}}"><input type="hidden" name="case_version" value="{{.Version}}"><input type="hidden" name="scope_type" value="{{.Scope.Type}}"><input type="hidden" name="scope_id" value="{{.Scope.ID}}"><select name="appeal_result"><option value="upheld">支持申诉</option><option value="denied">驳回申诉</option></select><input name="reason" maxlength="500" placeholder="复核原因" required><button class="btn btn-sm btn-outline-primary" type="submit">处理申诉</button></form>{{else if eq .Status "InvalidTraffic"}}<form method="post" action="trafficquality?action=enforce">{{$.Other.CSRFInput}}<input type="hidden" name="decision_id" value="{{.DecisionID}}"><input type="hidden" name="scope_type" value="{{.Scope.Type}}"><input type="hidden" name="scope_id" value="{{.Scope.ID}}"><select name="enforcement_action"><option>Throttle</option><option>Reject</option><option>Quarantine</option></select><input type="number" name="canary_bps" min="0" max="10000" value="100" aria-label="灰度基点"><input type="number" name="ttl_hours" min="1" max="720" value="24" aria-label="有效小时"><input name="reason" maxlength="500" placeholder="执行原因" required><button class="btn btn-sm btn-warning" type="submit">灰度执行</button></form>{{end}}</td></tr>{{else}}<tr><td colspan="6">所选范围暂无案件。</td></tr>{{end}}</tbody></table></div>
<h2 class="h4">执行记录</h2><div class="table-responsive"><table class="table table-sm"><thead><tr><th>ID</th><th>动作</th><th>状态</th><th>灰度</th><th>到期</th><th>回滚</th></tr></thead><tbody>{{range .Other.QualityEnforcements}}<tr><td>{{.ID}}</td><td>{{.Action}}</td><td>{{.State}}</td><td>{{.CanaryBasisPoints}} bp</td><td>{{.ExpiresAt}}</td><td>{{if or (eq .State "Active") (eq .State "Canary")}}<form method="post" action="trafficquality?action=rollback">{{$.Other.CSRFInput}}<input type="hidden" name="enforcement_id" value="{{.ID}}"><input type="hidden" name="scope_type" value="{{.Scope.Type}}"><input type="hidden" name="scope_id" value="{{.Scope.ID}}"><input name="reason" maxlength="500" placeholder="回滚原因" required><button class="btn btn-sm btn-danger" type="submit">回滚</button></form>{{end}}</td></tr>{{else}}<tr><td colspan="6">暂无执行记录。</td></tr>{{end}}</tbody></table></div>
{{ template "footer" .}}
