{{ template "header" .}}
<h1 class="h2">Traffic Quality Review</h1>
<p class="text-muted">Rule decisions are recorded separately from infrastructure errors. Every intervention requires complete evidence, human review, and a rollback-capable rule version.</p>
{{with .Other.QualityMessage}}<div class="alert alert-success">{{.}}</div>{{end}}
<div class="card mb-3"><div class="card-body"><h2 class="h5">Select Review Scope</h2><div class="form-row">
<form class="form-inline mr-3" method="get" action="trafficquality"><input type="hidden" name="action" value="topicsAdv"><label>Advertiser ID <input class="form-control ml-2" type="number" min="1" name="adv_id" required></label><button class="btn btn-outline-danger ml-2" type="submit">View</button></form>
<form class="form-inline mr-3" method="get" action="trafficquality"><input type="hidden" name="action" value="topicsPub"><label>Publisher ID <input class="form-control ml-2" type="number" min="1" name="pub_id" required></label><button class="btn btn-outline-info ml-2" type="submit">View</button></form>
<form class="form-inline" method="get" action="trafficquality"><input type="hidden" name="action" value="topicsPartner"><label>External Demand Partner ID <input class="form-control ml-2" type="number" min="1" name="partner_id" required></label><button class="btn btn-outline-secondary ml-2" type="submit">View</button></form>
</div></div></div>
<div class="card mb-3"><div class="card-body"><h2 class="h5">Create Rule Draft</h2><form method="post" action="trafficquality?action=createRule">{{.Other.CSRFInput}}<div class="form-row">
<div class="form-group col-md-3"><label>Rule Key</label><input class="form-control" name="rule_key" pattern="[a-z][a-z0-9_.-]{2,63}" required></div>
<div class="form-group col-md-3"><label>Signal</label><select class="form-control" name="signal"><option>Replay</option><option>ImpossibleSequence</option><option>InvalidOriginApp</option><option>MalformedIdentity</option><option>AbnormalRate</option><option>AbnormalCTR</option><option>Automation</option><option>PartnerPolicy</option></select></div>
<div class="form-group col-md-2"><label>Action</label><select class="form-control" name="rule_action"><option>Observe</option><option>Flag</option><option>Throttle</option><option>Reject</option><option>Quarantine</option></select></div>
<div class="form-group col-md-2"><label>Scope</label><select class="form-control" name="scope_type"><option>Global</option><option>Advertiser</option><option>Publisher</option><option>Partner</option></select></div>
<div class="form-group col-md-2"><label>Scope ID</label><input class="form-control" type="number" min="0" name="scope_id" value="0" required></div>
</div><div class="form-row">
<div class="form-group col-md-2"><label>Threshold</label><input class="form-control" type="number" min="0" step="0.000001" name="threshold" required></div>
<div class="form-group col-md-2"><label>Window (Seconds)</label><input class="form-control" type="number" min="1" max="2592000" name="window_seconds" value="60" required></div>
<div class="form-group col-md-2"><label>Reason Code</label><input class="form-control" name="reason_code" pattern="[a-z][a-z0-9_.-]{2,63}" required></div>
<div class="form-group col-md-2"><label>Evidence Retention (Hours)</label><input class="form-control" type="number" min="1" max="720" name="evidence_hours" value="24" required></div>
<div class="form-group col-md-2"><label>Aggregate Retention (Days)</label><input class="form-control" type="number" min="365" max="2555" name="aggregate_days" value="400" required></div>
<div class="form-group col-md-2"><label>False-Positive Limit (Basis Points)</label><input class="form-control" type="number" min="0" max="10000" name="false_positive_bps" value="100" required></div>
</div><label>Change Reason</label><input class="form-control" name="reason" maxlength="500" required><button class="btn btn-primary mt-2" type="submit">Save Draft</button></form></div></div>
<h2 class="h4">Rule Versions</h2><div class="table-responsive"><table class="table table-sm table-striped"><thead><tr><th>ID</th><th>Key / Version</th><th>Signal</th><th>Action</th><th>Scope</th><th>Threshold / Window</th><th>Mode</th><th>Publication</th></tr></thead><tbody>{{range .Other.QualityRules}}<tr><td>{{.ID}}</td><td><code>{{.Key}}@{{.Version}}</code></td><td>{{.Signal}}</td><td>{{.Action}}</td><td>{{.Scope.Type}} {{.Scope.ID}}</td><td>{{printf "%.6f" .Threshold}} / {{.WindowSeconds}} seconds</td><td>{{.Mode}}{{if eq .Mode "Canary"}} ({{.CanaryBasisPoints}} bp){{end}}</td><td><form method="post" action="trafficquality?action=setMode">{{$.Other.CSRFInput}}<input type="hidden" name="rule_id" value="{{.ID}}"><input type="hidden" name="expected_mode" value="{{.Mode}}"><select name="next_mode"><option>Observe</option><option>Canary</option><option>Active</option><option>Disabled</option></select><input type="number" name="canary_bps" min="0" max="10000" value="0" aria-label="Canary basis points"><input name="reason" maxlength="500" placeholder="Reason" required><button class="btn btn-sm btn-outline-primary" type="submit">Update</button></form></td></tr>{{else}}<tr><td colspan="8">No rules.</td></tr>{{end}}</tbody></table></div>
<h2 class="h4">Rule Health: Last 24 Hours</h2><table class="table table-sm"><thead><tr><th>Rule</th><th>Decisions / Matches / Enforced</th><th>Valid / Invalid</th><th>Appeals / Upheld</th><th>False-Positive Rate</th><th>Recommendation</th></tr></thead><tbody>{{range .Other.QualityHealth}}<tr><td><code>{{.RuleKey}}@{{.RuleVersion}}</code></td><td>{{.Decisions}} / {{.Matched}} / {{.Enforced}}</td><td>{{.ValidTraffic}} / {{.InvalidTraffic}}</td><td>{{.Appeals}} / {{.AppealsUpheld}}</td><td>{{.FalsePositiveBasisPoints}} bp (limit {{.FalsePositiveLimitBPS}})</td><td>{{if .RollbackRecommended}}<span class="badge badge-danger">Rollback Recommended</span>{{else}}Healthy{{end}}</td></tr>{{else}}<tr><td colspan="6">No rule-health data.</td></tr>{{end}}</tbody></table>
{{with .Other.QualityScope}}{{if ne .Type "Global"}}<h2 class="h4">Review Cases: {{.Type}} {{.ID}}</h2>{{end}}{{end}}
<div class="table-responsive"><table class="table table-sm"><thead><tr><th>Case</th><th>Rule</th><th>Signal / Evidence</th><th>Action</th><th>Status</th><th>Operations</th></tr></thead><tbody>{{range .Other.QualityCases}}<tr><td>#{{.ID}}<br><small>{{.ObservedAt}}</small></td><td><code>{{.RuleKey}}@{{.RuleVersion}}</code><br>{{.ReasonCode}}</td><td>{{.Signal}}: {{printf "%.6f" .ObservedValue}} / {{printf "%.6f" .Threshold}}<br>{{.Evidence}}{{if .SafeSummary.Valid}}: {{.SafeSummary.String}}{{end}}</td><td>{{.ConfiguredAction}} → {{.AppliedAction}}</td><td>{{.Status}} (v{{.Version}})</td><td>{{if eq .Status "Open"}}<form method="post" action="trafficquality?action=resolve">{{$.Other.CSRFInput}}<input type="hidden" name="case_id" value="{{.ID}}"><input type="hidden" name="case_version" value="{{.Version}}"><input type="hidden" name="scope_type" value="{{.Scope.Type}}"><input type="hidden" name="scope_id" value="{{.Scope.ID}}"><select name="resolution"><option>ValidTraffic</option><option>InvalidTraffic</option></select><input name="reason" maxlength="500" placeholder="Review reason" required><button class="btn btn-sm btn-outline-primary" type="submit">Close Case</button></form>{{else if eq .Status "Appealed"}}<form method="post" action="trafficquality?action=resolveAppeal">{{$.Other.CSRFInput}}<input type="hidden" name="case_id" value="{{.ID}}"><input type="hidden" name="case_version" value="{{.Version}}"><input type="hidden" name="scope_type" value="{{.Scope.Type}}"><input type="hidden" name="scope_id" value="{{.Scope.ID}}"><select name="appeal_result"><option value="upheld">Uphold Appeal</option><option value="denied">Deny Appeal</option></select><input name="reason" maxlength="500" placeholder="Review reason" required><button class="btn btn-sm btn-outline-primary" type="submit">Process Appeal</button></form>{{else if eq .Status "InvalidTraffic"}}<form method="post" action="trafficquality?action=enforce">{{$.Other.CSRFInput}}<input type="hidden" name="decision_id" value="{{.DecisionID}}"><input type="hidden" name="scope_type" value="{{.Scope.Type}}"><input type="hidden" name="scope_id" value="{{.Scope.ID}}"><select name="enforcement_action"><option>Throttle</option><option>Reject</option><option>Quarantine</option></select><input type="number" name="canary_bps" min="0" max="10000" value="100" aria-label="Canary basis points"><input type="number" name="ttl_hours" min="1" max="720" value="24" aria-label="Valid hours"><input name="reason" maxlength="500" placeholder="Enforcement reason" required><button class="btn btn-sm btn-warning" type="submit">Canary Enforcement</button></form>{{end}}</td></tr>{{else}}<tr><td colspan="6">No cases for selected scope.</td></tr>{{end}}</tbody></table></div>
<h2 class="h4">Enforcement Records</h2><div class="table-responsive"><table class="table table-sm"><thead><tr><th>ID</th><th>Action</th><th>Status</th><th>Canary</th><th>Expires</th><th>Rollback</th></tr></thead><tbody>{{range .Other.QualityEnforcements}}<tr><td>{{.ID}}</td><td>{{.Action}}</td><td>{{.State}}</td><td>{{.CanaryBasisPoints}} bp</td><td>{{.ExpiresAt}}</td><td>{{if or (eq .State "Active") (eq .State "Canary")}}<form method="post" action="trafficquality?action=rollback">{{$.Other.CSRFInput}}<input type="hidden" name="enforcement_id" value="{{.ID}}"><input type="hidden" name="scope_type" value="{{.Scope.Type}}"><input type="hidden" name="scope_id" value="{{.Scope.ID}}"><input name="reason" maxlength="500" placeholder="Rollback reason" required><button class="btn btn-sm btn-danger" type="submit">Rollback</button></form>{{end}}</td></tr>{{else}}<tr><td colspan="6">No enforcement records.</td></tr>{{end}}</tbody></table></div>
{{ template "footer" .}}
