{{ template "header" .}}{{ template "advheader" .}}
<div class="panel panel-default"><div class="panel-heading"><h3 class="panel-title">Account security</h3></div><div class="panel-body">
{{if .Other.Required}}<div class="alert alert-info">Two-factor authentication is required for this account type. Only this security page is available until enrollment is complete.</div>{{end}}
{{if .Other.Disabled}}<div class="alert alert-success">Two-factor authentication is disabled and all sessions were revoked. Sign in again and enroll promptly.</div>{{end}}
{{with .Other.Enrollment}}<div class="alert alert-warning"><p>Add this key to an authenticator and enter its current six-digit code. The key is displayed only once.</p><p><strong>Setup key:</strong> <code>{{.Secret}}</code></p><p class="text-break"><strong>Standard TOTP URI:</strong> <code>{{.URI}}</code></p></div><form method="post" action="security">{{$.Other.CSRFInput}}<input type="hidden" name="action" value="confirm"><div class="form-group"><label for="security-confirm-code">Six-digit code</label><input id="security-confirm-code" class="form-control" name="totp" inputmode="numeric" autocomplete="one-time-code" pattern="[0-9]{6}" required></div><button class="btn btn-primary" type="submit">Confirm and enable</button></form>{{end}}
{{with .Other.RecoveryCodes}}<div class="alert alert-success"><p><strong>Save these recovery codes offline now.</strong> Each is single-use and will not be shown again.</p><ul>{{range .}}<li><code>{{.}}</code></li>{{end}}</ul></div>{{end}}
<p>Status: <strong>{{.Other.MFAState}}</strong>; unused recovery codes: <strong>{{.Other.RecoveryRemaining}}</strong></p>
{{if eq .Other.MFAState "Disabled"}}<form method="post" action="security">{{.Other.CSRFInput}}<input type="hidden" name="action" value="enroll"><button class="btn btn-primary" type="submit">Set up authenticator</button></form>{{end}}
{{if eq .Other.MFAState "Enabled"}}<hr><h4>Rotate recovery codes</h4><form method="post" action="security">{{.Other.CSRFInput}}<input type="hidden" name="action" value="rotateRecovery"><div class="form-group"><label for="security-rotate-code">Current six-digit code</label><input id="security-rotate-code" class="form-control" name="totp" inputmode="numeric" autocomplete="one-time-code" pattern="[0-9]{6}" required></div><button class="btn btn-default" type="submit">Generate new codes</button></form><hr><h4>Disable two-factor authentication</h4><form method="post" action="security">{{.Other.CSRFInput}}<input type="hidden" name="action" value="disable"><div class="form-group"><label for="security-disable-code">Current six-digit code</label><input id="security-disable-code" class="form-control" name="totp" inputmode="numeric" autocomplete="one-time-code" pattern="[0-9]{6}" required></div><div class="form-group"><label for="security-disable-reason">Reason</label><input id="security-disable-reason" class="form-control" name="reason" maxlength="255" required></div><button class="btn btn-danger" type="submit">Disable and revoke all sessions</button></form>{{end}}
</div></div>{{ template "footer" .}}
