{{ template "header" .}}
{{ template "advheader" .}}
<div class="panel panel-default"><div class="panel-heading"><h3 class="panel-title">Account Security</h3></div><div class="panel-body">
{{if .Other.Required}}<div class="alert alert-info">Two-factor authentication is required for this account type. Until setup is complete, only the account-security page is available.</div>{{end}}
{{if .Other.Disabled}}<div class="alert alert-success">Two-factor authentication has been disabled and existing sessions have been revoked. Sign in again and set it up again as soon as possible.</div>{{end}}
{{with .Other.Enrollment}}<div class="alert alert-warning"><p>Add the following key to your authenticator, then enter the current six-digit code to confirm. The key is shown only once.</p><p><strong>Setup key:</strong> <code>{{.Secret}}</code></p><p class="text-break"><strong>Standard TOTP URI:</strong> <code>{{.URI}}</code></p></div>
<form method="post" action="security">{{$.Other.CSRFInput}}<input type="hidden" name="action" value="confirm"><div class="form-group"><label for="security-confirm-code">Six-digit code</label><input id="security-confirm-code" class="form-control" name="totp" inputmode="numeric" autocomplete="one-time-code" pattern="[0-9]{6}" required></div><button class="btn btn-primary" type="submit">Confirm and Enable</button></form>{{end}}
{{with .Other.RecoveryCodes}}<div class="alert alert-success"><p><strong>Save these recovery codes offline now.</strong> Each code can be used only once and will not be shown again after you leave this page.</p><ul>{{range .}}<li><code>{{.}}</code></li>{{end}}</ul></div>{{end}}
<p>Current status: <strong>{{.Other.MFAState}}</strong>; unused recovery codes: <strong>{{.Other.RecoveryRemaining}}</strong></p>
{{if eq .Other.MFAState "Disabled"}}<form method="post" action="security">{{.Other.CSRFInput}}<input type="hidden" name="action" value="enroll"><button class="btn btn-primary" type="submit">Set Up Authenticator</button></form>{{end}}
{{if eq .Other.MFAState "Enabled"}}<hr><h4>Refresh Recovery Codes</h4><p>After the refresh, previous recovery codes become invalid immediately.</p><form method="post" action="security">{{.Other.CSRFInput}}<input type="hidden" name="action" value="rotateRecovery"><div class="form-group"><label for="security-rotate-code">Current six-digit code</label><input id="security-rotate-code" class="form-control" name="totp" inputmode="numeric" autocomplete="one-time-code" pattern="[0-9]{6}" required></div><button class="btn btn-default" type="submit">Generate New Recovery Codes</button></form>
<hr><h4>Disable Two-Factor Authentication</h4><p>This revokes every session and records the reason for the operation.</p><form method="post" action="security">{{.Other.CSRFInput}}<input type="hidden" name="action" value="disable"><div class="form-group"><label for="security-disable-code">Current six-digit code</label><input id="security-disable-code" class="form-control" name="totp" inputmode="numeric" autocomplete="one-time-code" pattern="[0-9]{6}" required></div><div class="form-group"><label for="security-disable-reason">Reason</label><input id="security-disable-reason" class="form-control" name="reason" maxlength="255" required></div><button class="btn btn-danger" type="submit">Disable and Sign Out All Sessions</button></form>{{end}}
</div></div>
{{ template "footer" .}}
