{{template "header" .}}
<div class="container-fluid"><h1 class="h3">Publisher request credentials</h1>
<p class="text-muted">Use these App-scoped credentials only to sign <code>platform:"sdk"</code> requests to <code>POST /pz</code>. The private value is shown once; store it in an approved secret manager, never in mobile source.</p>
{{with .Other.IssuedPublisherPrivateValue}}<div class="alert alert-warning"><strong>Copy the new private credential now:</strong><br><code>{{.}}</code><br>It cannot be displayed again.</div>{{end}}
{{if .Other.PublisherCredentialListUnavailable}}<div class="alert alert-danger">The credential was issued, but the metadata list could not be refreshed. Preserve the private value above and retry the list later.</div>{{end}}
{{with .Other.RevokedPublisherCredentialID}}<div class="alert alert-success">Credential {{.}} was revoked.</div>{{end}}
<h2 class="h5">Issue credential</h2>
<form method="post" action="publishercredential?action=issue" autocomplete="off">{{.Other.CSRFInput}}<input type="hidden" name="pub_id" value="{{.Other.PublisherCredentialPubID}}"><label>Approved App site ID</label><input class="form-control" type="number" min="1" name="site_id" required><label>Name</label><input class="form-control" name="credential_name" maxlength="128" required><label>Lifetime (days)</label><input class="form-control" type="number" name="expires_days" min="1" max="365" value="90" required><label>Reason</label><input class="form-control" name="reason" maxlength="255" required><button class="btn btn-primary mt-2" type="submit">Issue credential</button></form>
<h2 class="h4 mt-4">Existing credentials</h2><div class="table-responsive"><table class="table table-sm table-striped"><thead><tr><th>ID</th><th>App site</th><th>Name / public ID</th><th>Expiry</th><th>State / action</th></tr></thead><tbody>{{range .Other.PublisherCredentials}}<tr><td>{{.ID}}</td><td>{{.SiteID}}</td><td>{{.Name}}<br><code>{{.PublicID}}</code></td><td>{{.ExpiresAt}}</td><td>{{if .RevokedAt}}Revoked{{else if .RotatedAt}}Rotated{{else}}Active{{end}}{{if not .RevokedAt}}<form method="post" action="publishercredential?action=rotate" autocomplete="off">{{$.Other.CSRFInput}}<input type="hidden" name="pub_id" value="{{$.Other.PublisherCredentialPubID}}"><input type="hidden" name="credential_id" value="{{.ID}}"><input class="form-control" type="number" name="overlap_minutes" min="0" max="10080" value="0" aria-label="Overlap minutes" required><input class="form-control" name="reason" maxlength="255" placeholder="Rotation reason" required><button class="btn btn-sm btn-warning" type="submit">Rotate</button></form><form method="post" action="publishercredential?action=revoke" autocomplete="off">{{$.Other.CSRFInput}}<input type="hidden" name="pub_id" value="{{$.Other.PublisherCredentialPubID}}"><input type="hidden" name="credential_id" value="{{.ID}}"><input class="form-control" name="reason" maxlength="255" placeholder="Revocation reason" required><button class="btn btn-sm btn-danger" type="submit">Revoke</button></form>{{end}}</td></tr>{{else}}<tr><td colspan="5">No publisher request credentials.</td></tr>{{end}}</tbody></table></div></div>
{{template "footer" .}}
