{{template "header" .}}
<div class="container-fluid"><h1 class="h3">流量方请求凭证</h1>
<p class="text-muted">凭证仅用于签名发送到 <code>POST /pz</code> 的 <code>platform:"sdk"</code> 请求，并且只授权一个已审核的 App。私密值只显示一次，请存入受控的密钥管理系统，不要写入移动端源码。</p>
{{with .Other.IssuedPublisherPrivateValue}}<div class="alert alert-warning"><strong>请立即复制新的私密凭证：</strong><br><code>{{.}}</code><br>离开本页后无法再次查看。</div>{{end}}
{{if .Other.PublisherCredentialListUnavailable}}<div class="alert alert-danger">凭证已签发，但元数据列表暂时无法刷新。请先安全保存上方私密值，稍后重试列表。</div>{{end}}
{{with .Other.RevokedPublisherCredentialID}}<div class="alert alert-success">凭证 {{.}} 已撤销。</div>{{end}}
<h2 class="h5">签发凭证</h2>
<form method="post" action="publishercredential?action=issue" autocomplete="off">{{.Other.CSRFInput}}<input type="hidden" name="pub_id" value="{{.Other.PublisherCredentialPubID}}"><label>已审核的 App 站点 ID</label><input class="form-control" type="number" min="1" name="site_id" required><label>名称</label><input class="form-control" name="credential_name" maxlength="128" required><label>有效期（天）</label><input class="form-control" type="number" name="expires_days" min="1" max="365" value="90" required><label>操作原因</label><input class="form-control" name="reason" maxlength="255" required><button class="btn btn-primary mt-2" type="submit">签发凭证</button></form>
<h2 class="h4 mt-4">现有凭证</h2><div class="table-responsive"><table class="table table-sm table-striped"><thead><tr><th>ID</th><th>App 站点</th><th>名称 / 公开标识</th><th>到期</th><th>状态 / 操作</th></tr></thead><tbody>{{range .Other.PublisherCredentials}}<tr><td>{{.ID}}</td><td>{{.SiteID}}</td><td>{{.Name}}<br><code>{{.PublicID}}</code></td><td>{{.ExpiresAt}}</td><td>{{if .RevokedAt}}已撤销{{else if .RotatedAt}}已轮换{{else}}生效中{{end}}{{if not .RevokedAt}}<form method="post" action="publishercredential?action=rotate" autocomplete="off">{{$.Other.CSRFInput}}<input type="hidden" name="pub_id" value="{{$.Other.PublisherCredentialPubID}}"><input type="hidden" name="credential_id" value="{{.ID}}"><input class="form-control" type="number" name="overlap_minutes" min="0" max="10080" value="0" aria-label="重叠分钟数" required><input class="form-control" name="reason" maxlength="255" placeholder="轮换原因" required><button class="btn btn-sm btn-warning" type="submit">轮换</button></form><form method="post" action="publishercredential?action=revoke" autocomplete="off">{{$.Other.CSRFInput}}<input type="hidden" name="pub_id" value="{{$.Other.PublisherCredentialPubID}}"><input type="hidden" name="credential_id" value="{{.ID}}"><input class="form-control" name="reason" maxlength="255" placeholder="撤销原因" required><button class="btn btn-sm btn-danger" type="submit">撤销</button></form>{{end}}</td></tr>{{else}}<tr><td colspan="5">尚未签发请求凭证。</td></tr>{{end}}</tbody></table></div></div>
{{template "footer" .}}
