{{ template "header" .}}
{{ template "ledgerheader" .}}
<div class="card"><div class="card-header">市场经营分析</div><div class="card-body">
<p>数据按 UTC 汇总，金额为 USD；应收、应付和毛利均为已换算的一次展示金额，不再除以 1000。报表只读。</p>
<form class="form-inline" method="get" action="ledger"><input type="hidden" name="action" value="topicsMarketplace"><label for="report-day">截止日期</label><input id="report-day" class="form-control" type="date" name="day" value="{{index .ARGS.day 0}}"><label for="report-lookback">回溯天数</label><input id="report-lookback" class="form-control" type="number" min="0" max="90" name="idays" value="{{index .ARGS.idays 0}}"><label for="report-limit">最多行数</label><input id="report-limit" class="form-control" type="number" min="1" max="200" name="top" value="{{index .ARGS.top 0}}"><button class="btn btn-primary" type="submit">查看</button><a class="btn btn-secondary" href="../json/ledger?action=topicsMarketplace&amp;day={{index .ARGS.day 0}}&amp;idays={{index .ARGS.idays 0}}&amp;top={{index .ARGS.top 0}}">导出 JSON</a></form>
</div></div>
<div class="card mt-3"><div class="card-header">数据新鲜度</div><div class="card-body">{{with .Other.ledger_topicsMarketplaceFreshness}}{{range .}}<p>投放事实：{{.report_state}}，更新至 {{.report_through}}；日报：{{.daily_state}}，更新至 {{.daily_through}}；转化接收：{{.action_state}}，更新至 {{.action_received_through}}；待处理合作方回调：{{.callback_backlog}}。</p>{{end}}{{end}}<p>依赖故障和回调积压必须显示为 partial / unavailable，不能按真实的零值解释。</p></div></div>
<div class="card mt-3"><div class="card-header">核心指标汇总</div><div class="card-body table-responsive"><table class="table table-sm table-hover"><thead><tr><th>曝光</th><th>点击</th><th>CTR</th><th>行为</th><th>CVR</th><th>广告主花费（USD）</th><th>购买金额（USD）</th><th>ROI</th><th>ROAS</th></tr></thead><tbody>{{with .Other.ledger_topicsMarketplaceSummary}}{{range .}}<tr><td>{{.impressions}}</td><td>{{.clicks}}</td><td>{{.ctr | printf "%.4f"}}</td><td>{{.actions}}</td><td>{{.cvr | printf "%.4f"}}</td><td>{{.spend_usd}}</td><td>{{.purchase_value_usd}}</td><td>{{.roi | printf "%.4f"}}</td><td>{{.roas | printf "%.4f"}}</td></tr>{{end}}{{end}}</tbody></table><p>行为与购买金额受转化保留期和接收高水位影响；比率为分析值，不是自动投放控制。</p></div></div>
<div class="card mt-3"><div class="card-header">经营维度明细</div><div class="card-body table-responsive"><table class="table table-sm table-hover"><thead><tr><th>来源</th><th>广告主 / 活动 / 广告组 / 素材</th><th>竞价端点 / 路由</th><th>流量方 / 流量源 / 广告位</th><th>流量分类 / 卖方</th><th>国家 / 地区</th><th>设备</th><th>胜 / 负 / 展示 / 点击</th><th>广告主花费</th><th>流量收入</th><th>外部成本</th><th>毛利</th><th>下游 / 返回 CPM</th><th>回调错误</th></tr></thead><tbody>{{range .Lists}}<tr><td>{{.demand_source}}</td><td>{{.adv_id}} / {{.campaign_id}} / {{.item_id}} / {{.creative_id}}</td><td>{{.bidder_name}} / {{.group_name}} / {{.route_bidder_id}} / {{.target_id}}</td><td>{{.pub_id}} / {{.site_id}} / {{.slot_id}}</td><td>{{.inventory_environment}} / {{.integration_mode}} / {{.media_intent}} / {{.placement}} / {{.refresh_mode}}{{if .refresh_seconds}}（{{.refresh_seconds}} 秒）{{end}} / {{.traffic_quality}} / {{.source_quality}} / {{.seller_type}}{{with .seller_id}} / {{.}}{{end}}</td><td>{{with .country_name}}{{.}}{{else}}未知{{end}}{{with .state_name}} / {{.}}{{end}}</td><td>{{.device_os_name}} / {{.device_type_name}}</td><td>{{.wins}} / {{.losses}} / {{.imps}} / {{.clis}}</td><td>{{.spend_usd}}</td><td>{{.revenue_usd}}</td><td>{{.cost_usd}}</td><td>{{.margin_usd}}</td><td>{{.downstream_cpm | printf "%.6f"}} / {{.returned_cpm | printf "%.6f"}}</td><td>{{.callback_errors}}</td></tr>{{end}}</tbody></table></div></div>
<div class="card mt-3"><div class="card-header">转化汇总</div><div class="card-body table-responsive"><table class="table table-sm table-hover"><thead><tr><th>广告主</th><th>活动 / 广告组 / 素材</th><th>行为类型</th><th>归因</th><th>行为数</th><th>迟到</th><th>购买金额（USD）</th></tr></thead><tbody>{{with .Other.ledger_topicsMarketplaceActions}}{{range .}}<tr><td>{{.adv_id}}</td><td>{{.campaign_id}} / {{.item_id}} / {{.creative_id}}</td><td>{{.event_type}}</td><td>{{.attribution_type}}</td><td>{{.actions}}</td><td>{{.late_actions}}</td><td>{{.purchase_value_usd}}</td></tr>{{end}}{{end}}</tbody></table></div></div>
{{ template "footer" }}
