{{ template "header" .}}
{{ template "ledgerheader" .}}
<div class="card"><div class="card-header">Marketplace Operations Analysis</div><div class="card-body">
<p>Data is aggregated in UTC and amounts are in USD. Receivables, payables, and margin are already converted per-impression amounts and must not be divided by 1,000 again. This report is read-only.</p>
<form class="form-inline" method="get" action="ledger"><input type="hidden" name="action" value="topicsMarketplace"><label for="report-day">Through Date</label><input id="report-day" class="form-control" type="date" name="day" value="{{index .ARGS.day 0}}"><label for="report-lookback">Lookback Days</label><input id="report-lookback" class="form-control" type="number" min="0" max="90" name="idays" value="{{index .ARGS.idays 0}}"><label for="report-limit">Maximum Rows</label><input id="report-limit" class="form-control" type="number" min="1" max="200" name="top" value="{{index .ARGS.top 0}}"><button class="btn btn-primary" type="submit">View</button><a class="btn btn-secondary" href="../json/ledger?action=topicsMarketplace&amp;day={{index .ARGS.day 0}}&amp;idays={{index .ARGS.idays 0}}&amp;top={{index .ARGS.top 0}}">Export JSON</a></form>
</div></div>
<div class="card mt-3"><div class="card-header">Data Freshness</div><div class="card-body">{{with .Other.ledger_topicsMarketplaceFreshness}}{{range .}}<p>Delivery facts: {{.report_state}}, through {{.report_through}}; daily report: {{.daily_state}}, through {{.daily_through}}; conversion receipt: {{.action_state}}, through {{.action_received_through}}; pending partner callbacks: {{.callback_backlog}}.</p>{{end}}{{end}}<p>Dependency failures and callback backlog must be shown as partial / unavailable and must not be interpreted as an actual zero value.</p></div></div>
<div class="card mt-3"><div class="card-header">Core-Metric Summary</div><div class="card-body table-responsive"><table class="table table-sm table-hover"><thead><tr><th>Impressions</th><th>Clicks</th><th>CTR</th><th>Actions</th><th>CVR</th><th>Advertiser Spend (USD)</th><th>Purchase Value (USD)</th><th>ROI</th><th>ROAS</th></tr></thead><tbody>{{with .Other.ledger_topicsMarketplaceSummary}}{{range .}}<tr><td>{{.impressions}}</td><td>{{.clicks}}</td><td>{{.ctr | printf "%.4f"}}</td><td>{{.actions}}</td><td>{{.cvr | printf "%.4f"}}</td><td>{{.spend_usd}}</td><td>{{.purchase_value_usd}}</td><td>{{.roi | printf "%.4f"}}</td><td>{{.roas | printf "%.4f"}}</td></tr>{{end}}{{end}}</tbody></table><p>Actions and purchase value are affected by conversion retention and the receipt high-water mark. Ratios are analytical values, not automatic delivery controls.</p></div></div>
<div class="card mt-3"><div class="card-header">Operations-Dimension Details</div><div class="card-body table-responsive"><table class="table table-sm table-hover"><thead><tr><th>Source</th><th>Advertiser / Campaign / Ad Group / Creative</th><th>Bid Endpoint / Route</th><th>Publisher / Traffic Source / Ad Slot</th><th>Traffic Classification / Seller</th><th>Country / Region</th><th>Device</th><th>Wins / Losses / Impressions / Clicks</th><th>Advertiser Spend</th><th>Traffic Revenue</th><th>External Cost</th><th>Margin</th><th>Downstream / Returned CPM</th><th>Callback Errors</th></tr></thead><tbody>{{range .Lists}}<tr><td>{{.demand_source}}</td><td>{{.adv_id}} / {{.campaign_id}} / {{.item_id}} / {{.creative_id}}</td><td>{{.bidder_name}} / {{.group_name}} / {{.route_bidder_id}} / {{.target_id}}</td><td>{{.pub_id}} / {{.site_id}} / {{.slot_id}}</td><td>{{.inventory_environment}} / {{.integration_mode}} / {{.media_intent}} / {{.placement}} / {{.refresh_mode}}{{if .refresh_seconds}} ({{.refresh_seconds}} seconds){{end}} / {{.traffic_quality}} / {{.source_quality}} / {{.seller_type}}{{with .seller_id}} / {{.}}{{end}}</td><td>{{with .country_name}}{{.}}{{else}}Unknown{{end}}{{with .state_name}} / {{.}}{{end}}</td><td>{{.device_os_name}} / {{.device_type_name}}</td><td>{{.wins}} / {{.losses}} / {{.imps}} / {{.clis}}</td><td>{{.spend_usd}}</td><td>{{.revenue_usd}}</td><td>{{.cost_usd}}</td><td>{{.margin_usd}}</td><td>{{.downstream_cpm | printf "%.6f"}} / {{.returned_cpm | printf "%.6f"}}</td><td>{{.callback_errors}}</td></tr>{{end}}</tbody></table></div></div>
<div class="card mt-3"><div class="card-header">Conversion Summary</div><div class="card-body table-responsive"><table class="table table-sm table-hover"><thead><tr><th>Advertiser</th><th>Campaign / Ad Group / Creative</th><th>Action Type</th><th>Attribution</th><th>Actions</th><th>Late</th><th>Purchase Value (USD)</th></tr></thead><tbody>{{with .Other.ledger_topicsMarketplaceActions}}{{range .}}<tr><td>{{.adv_id}}</td><td>{{.campaign_id}} / {{.item_id}} / {{.creative_id}}</td><td>{{.event_type}}</td><td>{{.attribution_type}}</td><td>{{.actions}}</td><td>{{.late_actions}}</td><td>{{.purchase_value_usd}}</td></tr>{{end}}{{end}}</tbody></table></div></div>
{{ template "footer" }}
